### ISSUE TITLE
[Bug] Slides review and code blocks are empty

### ISSUE THREAD

**Issue by rallisf1** [alvarosabu/slidev-theme-penguin#35]
Just need some css fixes.

Slidev has switched to shikiji-compat which is not 100% compatible with shiki

I am using the material theme myself, but that's just a personal reference and anyone can override with his own shiki.ts

**Comment by alvarosabu** [comment]
i fixed it in the last version https://github.com/alvarosabu/slidev-theme-penguin/releases/tag/v2.2.0
