### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by jesielviana** [alvarosabu/slidev-theme-penguin#8]
I installed the penguin theme, but it's not working.
When I open the slides, the following message appears:

Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/node_modules/slidev-theme-penguin/components/corner-curves/assets/curve-big.svg') is not a valid name.

**Comment by alvarosaburido** [comment]
Hey thanks for reporting @jesielviana . Did you install the last version? 

I also had the issue but I changed the assets from the location in this PR https://github.com/alvarosaburido/slidev-theme-penguin/pull/6 and worked. Let me know if it's still the case and I will check it

**Comment by border-1px** [comment]
hi，I installed v1.1.2 with the same error:

`
runtime-dom.esm-bundler.js:21 Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/node_modules/slidev-theme-penguin/components/corner-curves/assets/curve-big.svg') is not a valid name.`

**Comment by unotovive** [comment]
I couldn't start due to the same phenomenon

**Comment by alvarosaburido** [comment]
I'm gonna take care of this asap, thanks for reporting

**Comment by alvarosaburido** [comment]
@jesielviana @unotovive @border-1px  There is a workaround by installing this package [vite-svg-loader](https://www.npmjs.com/package/vite-svg-loader) and adding a `vite.config.js` on your project

```js
import svgLoader from 'vite-svg-loader'

export default {
  plugins: [svgLoader()],
}
```

I will try to investigate if there is a way of having this by default when installing instead of adding it manually. Let me know if it works I just tested it.

**Comment by unotovive** [comment]
@alvarosaburido 
Thank you for your quick reply.
I added it manually and it worked fine.

**Comment by lyqht** [comment]
> @jesielviana @unotovive @border-1px There is a workaround by installing this package [vite-svg-loader](https://www.npmjs.com/package/vite-svg-loader) and adding a `vite.config.js` on your project
> 
> ```js
> import svgLoader from 'vite-svg-loader'
> 
> export default {
>   plugins: [svgLoader()],
> }
> ```
> 
> I will try to investigate if there is a way of having this by default when installing instead of adding it manually. Let me know if it works I just tested it.

adding the svg loader helped!

**Comment by haudraufhaun** [comment]
When importing another svg file to display with a `img` tag, using svg-loader is breaking the build because the svg file included with the `<img/>` tag couldn't be imported right. Do you have any ideas to resolve this issue?
